const palette = {
  light: {
    text: "#0F172A",
    tint: "#1E40AF",
    background: "#F5F7FB",
    foreground: "#0F172A",
    card: "#FFFFFF",
    cardForeground: "#0F172A",
    primary: "#1E40AF",
    primaryDark: "#1E3A8A",
    primaryLight: "#3B82F6",
    primaryGlow: "#60A5FA",
    primaryForeground: "#FFFFFF",
    secondary: "#EEF2FF",
    secondaryForeground: "#1E3A8A",
    muted: "#F1F5F9",
    mutedForeground: "#64748B",
    accent: "#DBEAFE",
    accentForeground: "#1E3A8A",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E2E8F0",
    input: "#E2E8F0",
    success: "#10B981",
    gold: "#F59E0B",
    pattern: "#E0E7FF",
  },
  dark: {
    text: "#F8FAFC",
    tint: "#60A5FA",
    background: "#0B1220",
    foreground: "#F8FAFC",
    card: "#111B2E",
    cardForeground: "#F8FAFC",
    primary: "#3B82F6",
    primaryDark: "#1E3A8A",
    primaryLight: "#60A5FA",
    primaryGlow: "#93C5FD",
    primaryForeground: "#FFFFFF",
    secondary: "#1E293B",
    secondaryForeground: "#DBEAFE",
    muted: "#1E293B",
    mutedForeground: "#94A3B8",
    accent: "#1E3A8A",
    accentForeground: "#DBEAFE",
    destructive: "#F87171",
    destructiveForeground: "#FFFFFF",
    border: "#1E293B",
    input: "#1E293B",
    success: "#34D399",
    gold: "#FBBF24",
    pattern: "#1E293B",
  },
  radius: 20,
};

export default palette;
